name: Build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Build Release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Package
        shell: powershell
        run: |
          New-Item -ItemType Directory -Force -Path package
          Copy-Item target\release\xivcrafter.exe package\
          $tagName = "${env:GITHUB_REF}".Split('/')[-1]
          $zipName = "xivcrafter-rs-$tagName-windows.zip"
          Compress-Archive -Path package\* -DestinationPath $zipName
          echo "ZIP_NAME=$zipName" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ZIP_NAME }}
          path: ./*.zip
