name: Linter

on:
  push:
    paths:
    - '**.rs'
    branches:
    - '*'
  pull_request:
    paths:
    - '**.rs'
    branches:
    - '*'

jobs:
  clippy_check:
    name: Clippy Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3

    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        profile: minimal

    - name: Run clippy
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-targets -- -D warnings
